apiVersion: v1
kind: Template
metadata:
  name: ocp-inception-template
objects:
- apiVersion: kubevirt.io/v1alpha3
  kind: VirtualMachine
  metadata:
    annotations:
      kubevirt.io/latest-observed-api-version: v1alpha3
      kubevirt.io/storage-observed-api-version: v1alpha3
      kubevirt.ui/firstBoot: 'false'
      kubevirt.ui/pxeInterface: nic-0
      name.os.template.kubevirt.io/rhel8.2: Red Hat Enterprise Linux 8.0 or higher
    name: bootstrap
    namespace: ocp-inception
    labels:
      app: bootstrap
      os.template.kubevirt.io/rhel8.2: 'true'
      vm.kubevirt.io/template: rhel8-server-large-v0.11.3
      vm.kubevirt.io/template.namespace: openshift
      vm.kubevirt.io/template.revision: '1'
      vm.kubevirt.io/template.version: v0.11.3
      workload.template.kubevirt.io/server: 'true'
  spec:
    dataVolumeTemplates:
      - apiVersion: cdi.kubevirt.io/v1alpha1
        kind: DataVolume
        metadata:
          creationTimestamp: null
          name: bootstrap-rootdisk
        spec:
          pvc:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: ${ROOTDISK_VOLUME_SIZE}
            storageClassName: ${ROOTDISK_STORAGE_CLASS}
            volumeMode: ${ROOTDISK_VOLUME_MODE}
          source:
            blank: {}
    running: false
    template:
      metadata:
        creationTimestamp: null
        labels:
          kubevirt.io/domain: bootstrap
          kubevirt.io/size: large
          os.template.kubevirt.io/rhel8.2: 'true'
          vm.kubevirt.io/name: bootstrap
          workload.template.kubevirt.io/server: 'true'
      spec:
        domain:
          cpu:
            cores: 2
            model: Skylake-Client-noTSX-IBRS
            sockets: 1
            threads: 1
          devices:
            autoattachPodInterface: false
            disks:
              - disk:
                  bus: virtio
                name: disk-0
            interfaces:
              - bootOrder: 1
                bridge: {}
                macAddress: '52:54:00:60:72:67'
                model: virtio
                name: nic-0
            networkInterfaceMultiqueue: true
            rng: {}
          machine:
            type: pc-q35-rhel8.2.0
          resources:
            requests:
              memory: 8Gi
        hostname: bootstrap
        networks:
         - multus:
              networkName: ${DISCONNECTED_MULTUS_NET}
            name: nic-0
        terminationGracePeriodSeconds: 0
        volumes:
          - dataVolume:
              name: bootstrap-rootdisk
            name: disk-0

- apiVersion: kubevirt.io/v1alpha3
  kind: VirtualMachine
  metadata:
    annotations:
      kubevirt.io/latest-observed-api-version: v1alpha3
      kubevirt.io/storage-observed-api-version: v1alpha3
      kubevirt.ui/firstBoot: 'false'
      kubevirt.ui/pxeInterface: nic-0
      name.os.template.kubevirt.io/rhel8.2: Red Hat Enterprise Linux 8.0 or higher
    name: control-0
    namespace: ocp-inception
    labels:
      app: control-0
      os.template.kubevirt.io/rhel8.2: 'true'
      vm.kubevirt.io/template: rhel8-server-large-v0.11.3
      vm.kubevirt.io/template.namespace: openshift
      vm.kubevirt.io/template.revision: '1'
      vm.kubevirt.io/template.version: v0.11.3
      workload.template.kubevirt.io/server: 'true'
  spec:
    dataVolumeTemplates:
      - apiVersion: cdi.kubevirt.io/v1alpha1
        kind: DataVolume
        metadata:
          creationTimestamp: null
          name: control-0-rootdisk
        spec:
          pvc:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: ${ROOTDISK_VOLUME_SIZE}
            storageClassName: ${ROOTDISK_STORAGE_CLASS}
            volumeMode: ${ROOTDISK_VOLUME_MODE}
          source:
            blank: {}
    running: false
    template:
      metadata:
        creationTimestamp: null
        labels:
          kubevirt.io/domain: control-0
          kubevirt.io/size: large
          os.template.kubevirt.io/rhel8.2: 'true'
          vm.kubevirt.io/name: control-0
          workload.template.kubevirt.io/server: 'true'
      spec:
        domain:
          cpu:
            cores: 4
            model: Skylake-Client-noTSX-IBRS
            sockets: 1
            threads: 1
          devices:
            autoattachPodInterface: false
            disks:
              - disk:
                  bus: virtio
                name: disk-0
            interfaces:
              - bootOrder: 1
                bridge: {}
                macAddress: '52:54:00:e7:9d:67'
                model: virtio
                name: nic-0
            networkInterfaceMultiqueue: true
            rng: {}
          machine:
            type: pc-q35-rhel8.2.0
          resources:
            requests:
              memory: 12Gi
        hostname: control-0
        networks:
          - multus:
              networkName: ${DISCONNECTED_MULTUS_NET}
            name: nic-0
        terminationGracePeriodSeconds: 0
        volumes:
          - dataVolume:
              name: control-0-rootdisk
            name: disk-0

- apiVersion: kubevirt.io/v1alpha3
  kind: VirtualMachine
  metadata:
    annotations:
      kubevirt.io/latest-observed-api-version: v1alpha3
      kubevirt.io/storage-observed-api-version: v1alpha3
      kubevirt.ui/firstBoot: 'false'
      kubevirt.ui/pxeInterface: nic-0
      name.os.template.kubevirt.io/rhel8.2: Red Hat Enterprise Linux 8.0 or higher
    name: control-1
    namespace: ocp-inception
    labels:
      app: control-1
      os.template.kubevirt.io/rhel8.2: 'true'
      vm.kubevirt.io/template: rhel8-server-large-v0.11.3
      vm.kubevirt.io/template.namespace: openshift
      vm.kubevirt.io/template.revision: '1'
      vm.kubevirt.io/template.version: v0.11.3
      workload.template.kubevirt.io/server: 'true'
  spec:
    dataVolumeTemplates:
      - apiVersion: cdi.kubevirt.io/v1alpha1
        kind: DataVolume
        metadata:
          creationTimestamp: null
          name: control-1-rootdisk
        spec:
          pvc:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: ${ROOTDISK_VOLUME_SIZE}
            storageClassName: ${ROOTDISK_STORAGE_CLASS}
            volumeMode: ${ROOTDISK_VOLUME_MODE}
          source:
            blank: {}
    running: false
    template:
      metadata:
        creationTimestamp: null
        labels:
          kubevirt.io/domain: control-1
          kubevirt.io/size: large
          os.template.kubevirt.io/rhel8.2: 'true'
          vm.kubevirt.io/name: control-1
          workload.template.kubevirt.io/server: 'true'
      spec:
        domain:
          cpu:
            cores: 4
            model: Skylake-Client-noTSX-IBRS
            sockets: 1
            threads: 1
          devices:
            autoattachPodInterface: false
            disks:
              - disk:
                  bus: virtio
                name: disk-0
            interfaces:
              - bootOrder: 1
                bridge: {}
                macAddress: '52:54:00:80:16:23'
                model: virtio
                name: nic-0
            networkInterfaceMultiqueue: true
            rng: {}
          machine:
            type: pc-q35-rhel8.2.0
          resources:
            requests:
              memory: 12Gi
        hostname: control-1
        networks:
          - multus:
              networkName: ${DISCONNECTED_MULTUS_NET}
            name: nic-0
        terminationGracePeriodSeconds: 0
        volumes:
          - dataVolume:
              name: control-1-rootdisk
            name: disk-0

- apiVersion: kubevirt.io/v1alpha3
  kind: VirtualMachine
  metadata:
    annotations:
      kubevirt.io/latest-observed-api-version: v1alpha3
      kubevirt.io/storage-observed-api-version: v1alpha3
      kubevirt.ui/firstBoot: 'false'
      kubevirt.ui/pxeInterface: nic-0
      name.os.template.kubevirt.io/rhel8.2: Red Hat Enterprise Linux 8.0 or higher
    name: control2
    namespace: ocp-inception
    labels:
      app: control-2
      os.template.kubevirt.io/rhel8.2: 'true'
      vm.kubevirt.io/template: rhel8-server-large-v0.11.3
      vm.kubevirt.io/template.namespace: openshift
      vm.kubevirt.io/template.revision: '1'
      vm.kubevirt.io/template.version: v0.11.3
      workload.template.kubevirt.io/server: 'true'
  spec:
    dataVolumeTemplates:
      - apiVersion: cdi.kubevirt.io/v1alpha1
        kind: DataVolume
        metadata:
          creationTimestamp: null
          name: control-2-rootdisk
        spec:
          pvc:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: ${ROOTDISK_VOLUME_SIZE}
            storageClassName: ${ROOTDISK_STORAGE_CLASS}
            volumeMode: ${ROOTDISK_VOLUME_MODE}
          source:
            blank: {}
    running: false
    template:
      metadata:
        creationTimestamp: null
        labels:
          kubevirt.io/domain: control-2
          kubevirt.io/size: large
          os.template.kubevirt.io/rhel8.2: 'true'
          vm.kubevirt.io/name: control-2
          workload.template.kubevirt.io/server: 'true'
      spec:
        domain:
          cpu:
            cores: 4
            model: Skylake-Client-noTSX-IBRS
            sockets: 1
            threads: 1
          devices:
            autoattachPodInterface: false
            disks:
              - disk:
                  bus: virtio
                name: disk-0
            interfaces:
              - bootOrder: 1
                bridge: {}
                macAddress: '52:54:00:d5:1c:39'
                model: virtio
                name: nic-0
            networkInterfaceMultiqueue: true
            rng: {}
          machine:
            type: pc-q35-rhel8.2.0
          resources:
            requests:
              memory: 12Gi
        hostname: control-2
        networks:
          - multus:
              networkName: ${DISCONNECTED_MULTUS_NET}
            name: nic-0
        terminationGracePeriodSeconds: 0
        volumes:
          - dataVolume:
              name: control-2-rootdisk
            name: disk-0

parameters:
  - name: ROOTDISK_VOLUME_SIZE
  - name: ROOTDISK_VOLUME_MODE
  - name: ROOTDISK_STORAGE_CLASS
  - name: DISCONNECTED_MULTUS_NET
